-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "SIMOX" SALT 'cc379fcfc35cecbf' HASH '4928db46f698ecba66a0eb84b80e3fb8ac6e3a7dace44e1e24fdad138f9e1e5a' ADMIN;      
CREATE MEMORY TABLE "PUBLIC"."CIRELATION"(
    "C_ID" INTEGER NOT NULL,
    "I_ID" INTEGER NOT NULL,
    "I_QUANTITY" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."CIRELATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("C_ID", "I_ID");         
-- 356 +/- SELECT COUNT(*) FROM PUBLIC.CIRELATION;            
INSERT INTO "PUBLIC"."CIRELATION" VALUES
(1, 1, '45 ml'),
(1, 2, '30 ml'),
(1, 3, '22.5 ml'),
(1, 4, '15 ml'),
(2, 5, '30 ml'),
(2, 6, '30 ml'),
(2, 7, '30 ml'),
(3, 8, '30 ml'),
(3, 9, '30 ml'),
(3, 10, 'A splash'),
(4, 11, '30 ml'),
(4, 12, '30 ml'),
(4, 13, '30 ml'),
(5, 11, '45 ml'),
(5, 14, '15 ml'),
(5, 3, '15 ml'),
(5, 15, '1 Bar Spoon'),
(6, 16, '45 ml'),
(6, 17, '15 ml'),
(6, 18, '60 ml'),
(6, 19, '1 dash'),
(6, 20, 'Top up'),
(7, 21, '52.5 ml'),
(7, 22, '2 teaspoons'),
(7, 3, '22.5 ml'),
(7, 23, '22.5 ml'),
(8, 20, '100 ml'),
(8, 24, '50 ml'),
(9, 25, '30 ml'),
(9, 5, '30 ml'),
(9, 26, '30 ml'),
(9, 3, '20 ml'),
(10, 27, '50 ml'),
(10, 28, '20 ml'),
(11, 27, '45 ml'),
(11, 29, '90 ml'),
(11, 3, '15 ml'),
(11, 30, '2 dashes'),
(11, 31, 'Up to taste'),
(11, 32, 'Up to taste'),
(11, 33, 'Up to taste'),
(12, 34, '45 ml'),
(12, 8, '30 ml'),
(12, 9, '30 ml'),
(13, 11, '50 ml'),
(13, 3, '25 ml'),
(13, 35, '12,5 ml'),
(13, 36, '15 ml'),
(14, 37, '52,5 ml'),
(14, 14, '7,5 ml'),
(14, 38, '1 Bar Spoon'),
(14, 3, '15 ml'),
(14, 39, '1 Bar Spoon'),
(14, 40, '2 Dashes'),
(15, 41, '60 ml'),
(15, 19, '15 ml'),
(15, 42, '15 ml'),
(15, 43, '50 ml'),
(16, 44, '60 ml'),
(16, 45, '1 (cut into small wedges)'),
(16, 46, '4 Teaspoons'),
(17, 47, '40 ml'),
(17, 14, '10 ml'),
(17, 3, '10 ml'),
(17, 48, '2 Dashes'),
(18, 49, '90 ml'),
(18, 5, '10 ml'),
(18, 1, '2 dashes'),
(18, 50, 'Few drops (Optional)'),
(18, 51, '1'),
(19, 11, '45 ml'),
(19, 52, '15 ml'),
(19, 3, '15 ml'),
(19, 53, 'Few Drops'),
(20, 11, '30 ml'),
(20, 54, '30 ml'),
(20, 55, '30 ml'),
(20, 3, '30 ml'),
(20, 56, '1 dash'),
(21, 57, '40 ml'),
(21, 54, '15 ml'),
(21, 19, '15 ml'),
(21, 58, '30 ml'),
(22, 25, '50 ml'),
(22, 59, '120ml'),
(22, 19, '10 ml'),
(23, 60, '60 ml'),
(23, 19, '20 ml'),
(23, 61, '2 Bar Spoons'),
(24, 62, '60 ml'),
(24, 63, '100 ml'),
(25, 11, '60 ml'),
(25, 64, '10 ml'),
(26, 27, '50 ml'),
(26, 65, '30 ml'),
(26, 35, '10 ml'),
(26, 66, '1'),
(27, 67, '50 ml'),
(27, 68, 'Fill up'),
(28, 11, '30 ml'),
(28, 3, '15 ml'),
(28, 35, '15 ml'),
(28, 69, '60 ml'),
(29, 5, '35 ml'),
(29, 70, '35 ml'),
(30, 27, '45 ml'),
(30, 71, '15 ml'),
(30, 18, '15 ml'),
(31, 11, '45 ml'),
(31, 3, '30 ml'),
(31, 39, '10 ml'),
(31, 10, 'Splash'),
(32, 17, '20 ml'),
(32, 26, '20 ml'),
(32, 23, '20 ml'),
(32, 7, '10 ml'),
(33, 72, '20 ml'),
(33, 73, '20 ml'),
(33, 7, '20 ml'),
(34, 74, '45 ml'),
(34, 9, '45 ml'),
(34, 67, '7.5 ml'),
(35, 75, '60 ml'),
(35, 76, '40 ml'),
(35, 14, '15 ml'),
(35, 77, '15 ml'),
(36, 5, '40 ml'),
(36, 78, '120 ml'),
(36, 1, 'Dash (optional)'),
(37, 79, '30 ml'),
(37, 80, '15 ml'),
(37, 81, '15 ml'),
(37, 14, '1 Bar Spoon'),
(37, 19, '22.5 ml'),
(37, 39, '15 ml'),
(37, 53, 'Few Drops (Optional)'),
(38, 82, '50 ml'),
(38, 83, '120 ml'),
(38, 7, '50 ml (Chilled)'),
(38, 84, '1 teaspoon'),
(39, 11, '45 ml'),
(39, 3, '30 ml'),
(39, 39, '15 ml'),
(39, 10, '60 ml'),
(40, 85, '90 ml'),
(40, 86, '10 ml'),
(41, 11, '22.5 ml'),
(41, 87, '22.5 ml'),
(41, 14, '22.5 ml'),
(41, 19, '22.5 ml'),
(42, 88, '30 ml'),
(42, 26, '20 ml'),
(42, 3, '15 ml'),
(43, 27, '15 ml'),
(43, 89, '15 ml'),
(43, 25, '15 ml'),
(43, 11, '15 ml'),
(43, 54, '15 ml'),
(43, 3, '30 ml'),
(43, 39, '20 ml'),
(43, 68, 'Top up'),
(44, 90, '30 ml'),
(44, 91, '30 ml'),
(44, 92, '15 ml'),
(44, 2, '15 ml'),
(44, 19, '30 ml'),
(44, 39, '7.5 ml'),
(45, 4, '50 ml'),
(45, 9, '20 ml'),
(45, 1, '1 dash'),
(46, 93, '50 ml'),
(46, 26, '20 ml'),
(46, 94, '15 ml'),
(47, 74, '45 ml'),
(47, 9, '45 ml'),
(47, 95, '1 Bar Spoon'),
(47, 48, '2 Dashes'),
(48, 25, '45 ml'),
(48, 18, '45 ml'),
(48, 14, '7.5 ml'),
(48, 96, '5 ml'),
(49, 23, '75 ml'),
(49, 20, '75 ml'),
(50, 97, '60 ml'),
(50, 98, '4'),
(50, 99, '1 tsp'),
(50, 43, '2 tsp'),
(51, 60, '45 ml'),
(51, 19, '20 ml'),
(51, 100, '6 pcs'),
(51, 46, '2 tsp'),
(51, 10, 'Top up'),
(52, 21, '45 ml'),
(52, 23, '45 ml'),
(52, 56, '1 Table Spoon'),
(52, 96, '1 Table Spoon'),
(53, 101, '45 ml'),
(53, 63, '120 ml'),
(53, 19, '10 ml'),
(54, 102, '22.5 ml'),
(54, 103, '22.5 ml'),
(54, 104, '22.5 ml'),
(54, 19, '22.5 ml'),
(55, 11, '30 ml'),
(55, 8, '30 ml'),
(55, 9, '30 ml');            
INSERT INTO "PUBLIC"."CIRELATION" VALUES
(56, 34, '60 ml'),
(56, 39, '22.5 ml'),
(56, 3, '30 ml'),
(56, 53, 'Few Drops'),
(56, 105, '15 ml'),
(57, 106, '6/8 pcs'),
(57, 107, '45 ml'),
(57, 19, '22.5 ml'),
(57, 39, '30 ml'),
(57, 1, '2 Dashes'),
(57, 108, '60 ml'),
(58, 34, '45 ml'),
(58, 51, '1'),
(58, 1, 'Few Dashes'),
(58, 109, 'Few Dashes'),
(59, 110, '50 ml'),
(59, 77, '5 ml'),
(59, 111, 'A pinch'),
(59, 112, '100 ml'),
(60, 97, '30 ml'),
(60, 113, '30 ml'),
(60, 104, '30 ml'),
(60, 3, '30 ml'),
(61, 11, '30 ml'),
(61, 12, '20 ml'),
(61, 23, '15 ml'),
(62, 114, '60 ml'),
(62, 115, '7.5 ml'),
(62, 3, '22.5 ml'),
(62, 22, '22.5 ml'),
(62, 116, '2-3 quarter size'),
(63, 25, '50 ml'),
(63, 117, '30 ml'),
(63, 18, '50 ml'),
(64, 118, '60 ml'),
(64, 3, '30 ml'),
(64, 39, '20 ml'),
(64, 53, '1 Raw'),
(65, 119, '45 ml'),
(65, 120, '15 ml'),
(65, 121, '30 ml'),
(66, 37, '15 ml'),
(66, 122, '45 ml'),
(66, 123, '10 ml'),
(67, 11, '45 ml'),
(67, 19, '15 ml'),
(67, 3, '15 ml'),
(67, 35, '30 ml'),
(67, 124, '60 ml'),
(67, 53, '30ml'),
(67, 125, '3 Dashes'),
(67, 126, '2 Drops'),
(67, 10, 'Top up'),
(68, 27, '25 ml'),
(68, 3, '25 ml'),
(68, 86, '15 ml'),
(68, 35, '10 ml'),
(68, 127, 'Top up'),
(69, 128, '45 ml'),
(69, 129, '25ml'),
(70, 5, '50 ml'),
(70, 56, '10 ml'),
(70, 51, '1'),
(70, 130, '2 Dashes'),
(71, 27, '40 ml'),
(71, 58, '120 ml'),
(71, 76, '30 ml'),
(72, 27, '40 ml'),
(72, 131, '20 ml'),
(72, 23, '40 ml'),
(72, 58, '40 ml'),
(73, 5, '50 ml'),
(73, 26, '20 ml'),
(73, 3, '20 ml'),
(74, 11, '30 ml'),
(74, 132, '15 ml'),
(74, 54, '7.5 ml'),
(74, 133, '7.5 ml'),
(74, 18, '120 ml'),
(74, 19, '15 ml'),
(74, 96, '10 ml'),
(74, 1, 'A dash'),
(75, 74, '60 ml'),
(75, 3, '30 ml'),
(75, 39, '15 ml'),
(75, 106, '5/6'),
(75, 53, 'Few Drops (Optional)'),
(76, 134, '50 ml'),
(76, 135, '15 ml'),
(76, 19, '15 ml'),
(76, 136, '10 ml'),
(76, 137, '2 thin Slices'),
(77, 20, '90 ml'),
(77, 104, '60 ml'),
(77, 10, 'Splash'),
(78, 5, '50 ml'),
(78, 138, '20 ml'),
(79, 139, '30 ml'),
(79, 11, '30 ml'),
(79, 19, '15 ml'),
(79, 1, '2 Dashes'),
(79, 63, 'Top up'),
(80, 89, '45ml'),
(80, 23, '90 ml'),
(80, 96, '15 ml'),
(81, 82, '50 ml'),
(81, 9, '25 ml'),
(81, 87, '15 ml'),
(81, 1, '2 Dashes'),
(82, 140, '60 ml'),
(82, 141, '30 ml'),
(82, 142, '30 ml'),
(83, 47, '30 ml'),
(83, 64, '30 ml'),
(83, 14, '1/2 Bar Spoon'),
(83, 56, '1/4 Bar Spoon'),
(83, 48, '3 Dashes'),
(84, 143, '45 ml'),
(84, 3, '22.5 ml'),
(84, 144, '15 ml'),
(84, 145, '15 ml'),
(84, 53, '10ml (Optional)'),
(85, 11, '45 ml'),
(85, 27, '15 ml'),
(85, 55, '7.5 ml'),
(86, 4, '30 ml'),
(86, 5, '30 ml'),
(86, 146, '30 ml'),
(86, 147, '1 Bar Spoon'),
(86, 130, '2 Dashes'),
(87, 97, '45 ml'),
(87, 3, '25 ml'),
(87, 35, '20 ml'),
(87, 148, '20 ml'),
(88, 11, '40 ml'),
(88, 26, '30 ml'),
(88, 3, '20 ml'),
(89, 25, '30 ml'),
(89, 17, '15 ml'),
(89, 26, '15 ml'),
(89, 19, '15 ml'),
(90, 149, '45 ml'),
(90, 150, '45 ml'),
(90, 151, '30 ml'),
(90, 19, '20 ml'),
(90, 81, '15 ml'),
(90, 152, '15 ml'),
(90, 96, '1 tsp'),
(90, 1, '1 dash'),
(90, 153, '6 drops');          
CREATE MEMORY TABLE "PUBLIC"."COCKTAIL"(
    "ID" INTEGER NOT NULL,
    "CATEGORY" CHARACTER VARYING(255),
    "GARNISH" CHARACTER VARYING(255),
    "HISTORY" CHARACTER VARYING,
    "IMAGEURL" CHARACTER VARYING(255),
    "LINK" CHARACTER VARYING(255),
    "METHOD" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255),
    "NOTE" CHARACTER VARYING(255),
    "SIMOXRATE" INTEGER
);       
ALTER TABLE "PUBLIC"."COCKTAIL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");     
-- 90 +/- SELECT COUNT(*) FROM PUBLIC.COCKTAIL;               
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(1, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-24-Trinidad-Sour.jpg', 'https://iba-world.com/trinidad-sour/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Trinidad Sour', 'N/A', 3),
(2, 'The Unforgettables', 'Sprinkle fresh ground nutmeg on top.', 'The Alexander cocktail was born in London in 1922 by Hery Mc Elhone, at Ciro''s Club in honor of a famous bride, at the beginning it was called Panama, Gin was used instead of Cognac and light cocoa cream instead of dark. Throughout its history, Alexander has given rise to many other variations: 1) Grasshopper: This variant is also part of the Iba list and involves the use of creme de menthe verde instead of cognac. 2) Alexandra: Use the light cocoa cream instead of the dark one and replace the nutmeg with cocoa. 3) Alexander''s Sister: Use creme de menthe instead of creme de cacao. 4) Alejandro: Replace cognac with rum.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-01-Alexander.jpg', 'https://iba-world.com/alexander/', 'Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.', 'Alexander', 'N/A', 3),
(3, 'The Unforgettables', 'Garnish with half orange slice and a lemon zest.', 'The story of the Americano dates back to the second half of the 1800s in Gaspare Campari''s bar in Milan. Over the years the cocktail acquires notoriety thanks to some homages from the world of cinema, including James Bond (007 Casino Royale) whose favorite cocktail was, precisely, the Americano. The nickname "American" was born when Primo Carnera, a giant Italian boxer, became world heavyweight champion at Madison Square Garden in New York.  When Carnera returned to Italy with the title, he was greeted with this very Italian cocktail which, for the occasion, was called "Americano". The Americano entered the IBA Cocktail List only in 1987 but, in reality, it was a cocktail that spread all over Italy during the 1930s.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-02-Americano.jpg', 'https://iba-world.com/americano/', 'Mix the ingredients directly in an old fashioned glass filled with ice cubes. Add a splash of Soda Water. Stir gently.', 'Americano', 'N/A', 6),
(4, 'The Unforgettables', 'N/A', 'Although the origin of the cocktail is not known, the main hypotheses assume that it was born in the twenties of the twentieth century in France: this thesis would prove the presence of calvados, a liqueur commonly used in France and, in particular, in that period, as an epidemic of phylloxera in European vineyards had limited the production of brandy. On this basis, one of the most frequent hypotheses has it that the cocktail was created by Harry MacElhone, founder of Harry''s New York Bar in Paris on July 19, 1919, in honor of the celebrations for the victory of the First World War. The first reliable evidence, however, dates back to 1930 when Harry Craddock included the Angel Face among the recipes of his book "Savoy cocktail book". Some sources indicate that the name derives from that of an American gangster active during Prohibition; less likely the dedication to Rick Blaine, the protagonist of Casablanca played by Humphrey Bogart, as the film follows the first testimonies (1942).', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-03-Angel-Face.jpg', 'https://iba-world.com/angel-face/', 'Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.', 'Angel Face', 'N/A', 3),
(5, 'The Unforgettables', 'Optional Maraschino Cherry.', U&'Aviation was created in New York at the Walkick hotel by the head bartender Hugo Ensslin while he was writing his book "Recipes for Mixed Drinks" (1916) one of the last cocktail books published before the start of American Prohibition. Lately David Wondrich found the aviation recipe in a 1911 magazine, so the recipe is thought to have been born earlier then 1916. In his book Ensslin also indicates the type of Gin to be used \2018El Bart Gin "and the recipe is made up in addition to gin, with lemon juice, maraschino Luxardo and Creme di Violette. The recipe is found again in Harry Craddock''s 1930 Savoy Cocktail Book but without the Creme de Violette, this probably due to the difficulty of finding the violet cream during the post-war period In the 1960s it was still unavailable and therefore, simply, the basic ingredient of the Aviation cocktail was discontinued and the bartenders definitively gave up the characteristic blue color of the drink. The IBA proposes it today in its original version with the creme de violette which is now on the market again. This fragrant ingredient not only gave the mix a sweetly floral taste, but also gave it a beautiful sky blue color.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-04-Aviation.jpg', 'https://iba-world.com/692/', 'Add all ingredients into a cocktail shaker. Shake with cracked ice and strain into a chilled cocktail glass.', 'Aviation', 'N/A', 4);     
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(6, 'New Era Drinks', 'Pineapple and Cherry, optional mint sprig for additional aroma.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-01-Barracuda.jpg', 'https://iba-world.com/barracuda/', 'Pour all ingredients into cocktail shaker except the Prosecco, shake well with ice, strain into chilled highball glass filled with ice and top up with Prosecco.', 'Barracuda', 'N/A', 4),
(7, 'New Era Drinks', 'Optionally garnish with a lemon or orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-03-Bees-Knees.jpg', 'https://iba-world.com/bees-knees/', 'Stir honey with lemon and orange juices until it dissolves, add gin and shake with ice. Strain into a chilled cocktail glass.', 'Bee''s Knees', 'N/A', 10),
(8, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-01-Bellini-scaled.jpg', 'https://iba-world.com/bellini/', 'Pour peach puree into the mixing glass with ice, add the Prosecco wine. Stir gently and pour in a chilled flute glass.', 'Bellini', 'Puccini - Fresh Mandarin Orange Juice; Rossini - Fresh Strawberry Puree; Tintoretto - Fresh Pomegranate Juice.', 5),
(9, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-05-Between-The-Sheets.jpg', 'https://iba-world.com/between-the-sheets/', 'Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.', 'Between the Sheets', 'N/A', 3),
(10, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-02-Black-Russian-scaled.jpg', 'https://iba-world.com/black-russian/', 'Pour the ingredients into the old fashioned glass filled with ice cubes. Stir gently.', 'Black Russian', 'White Russian - Float fresh cream on the top and stir in slowly.', 8),
(11, 'Contemporary Classics', 'Celery, Lemon Wedge (Optional)', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-03-Bloody-Marry-scaled.jpg', 'https://iba-world.com/bloody-mary/', 'Stir gently all the ingredients in a mixing glass with ice, pour into rocks glass.', 'Bloody Mary', 'If requested served with ice, pour into highball glass.', 5),
(12, 'The Unforgettables', 'Garnish with orange zest, optionally a lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-06-Boulevardier.jpg', 'https://iba-world.com/boulevardier/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Boulevardier', 'N/A', 5),
(13, 'New Era Drinks', 'Garnish optionally with a lemon slice and blackberries.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-02-Bramble.jpg', 'https://iba-world.com/bramble/', 'Pour all ingredients into a cocktail shaker except the Creme de Mure, shake well with ice, strain into chilled old fashioned glass filled with crushed ice, then pour the blackberry liqueur (Creme de Mure) over the top of the drink, in a circular motion.', 'Bramble', 'N/A', 6),
(14, 'The Unforgettables', 'Rub a slice of orange (or lemon) around the rim of the glass and dip it in pulverized white sugar, so that the sugar will adhere to the edge of the glass. Carefully curling place the orange/lemon peel around the inside of the glass.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-07-Brandy-Crusta.jpg', 'https://iba-world.com/brandy-crusta/', 'Mix together all ingredients with ice cubes in a mixing glass and strain into prepared slim cocktail glass.', 'Brandy Crusta', 'N/A', 1),
(15, 'New Era Drinks', 'Lime wedge.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-04-Cachanchara.jpg', 'https://iba-world.com/cachanchara/', 'Mix honey with water and lime juice and spread the mixture on the bottom and sides of the glass. Add cracked ice, and then the rum. End by energetically stirring from bottom to top.', 'Canchanchara', 'N/A', 7),
(16, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-04-Caipirinha-scaled.jpg', 'https://iba-world.com/caipirinha/', U&'Place lime and sugar into a double old fashioned glass and muddle gently. Fill the glass with cracked ice and add Cacha\00e7a. Stir gently to involve ingredients.', 'Caipirinha', U&'Caipiroska - Instead of Cacha\00e7a use Vodka;', 6);         
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(17, 'The Unforgettables', 'Garnish with lemon zest and a maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-08-Casino.jpg', 'https://iba-world.com/casino/', 'Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled rocks glass with ice.', 'Casino', 'N/A', 5),
(18, 'Contemporary Classics', 'Garnish with orange zest and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-05-Champagne-Cocktail-scaled.jpg', 'https://iba-world.com/champagne-cocktail/', 'Place the sugar cube with 2 dashes of bitters in a large Champagne glass, add the cognac. Pour gently chilled Champagne.', 'Champagne Cocktail', 'N/A', 2),
(19, 'The Unforgettables', 'Fresh raspberries.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-09-Clover-Club.jpg', 'https://iba-world.com/clover-club/', 'Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled cocktail glass.', 'Clover Club', 'N/A', 7),
(20, 'Contemporary Classics', 'Garnish with orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-07-Corpse-Reviver2-scaled.jpg', 'https://iba-world.com/corpse-reviver-2/', 'Pour all ingredients into shaker with ice. Shake well and strain in chilled cocktail glass.', 'Corpse Reviver #2', 'N/A', 2),
(21, 'Contemporary Classics', 'Garnish with a lemon twist.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-06-Cosmopolitan-scaled.jpg', 'https://iba-world.com/cosmopolitan/', 'Add all ingredients into a cocktail shaker filled with ice. Shake well and strain into a large cocktail glass.', 'Cosmopolitan', 'N/A', 2),
(22, 'Contemporary Classics', 'Garnish with lime wedge.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-08-Cuba-Libre-scaled.jpg', 'https://iba-world.com/cuba-libre/', 'Build all ingredients in a highball glass filled with ice.', 'Cuba Libre', 'N/A', 10),
(23, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-10-Daiquiri.jpg', 'https://iba-world.com/daiquiri/', 'In a cocktail shaker add all ingredients. Stir well to dissolve the sugar. Add ice and shake. Strain into chilled cocktail glass.', 'Daiquiri', 'N/A', 10),
(24, 'New Era Drinks', 'Garnish with a lime wedge or slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-05-DarkNStormy.jpg', 'https://iba-world.com/dark-n-stormy/', 'In a highball glass filled with ice pour the ginger beer and top floating with the Rum.', U&'Dark \2018n'' stormy', 'N/A', 7),
(25, 'The Unforgettables', 'Squeeze oil from lemon peel onto the drink, or garnish with green olives if requested.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-11-Dry-Martini.jpg', 'https://iba-world.com/dry-martini/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Dry Martini', 'N/A', 7),
(26, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-06-Espresso-Martini.jpg', 'https://iba-world.com/espresso-martini/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Espresso Martini', 'N/A', 8),
(27, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-07-Fernandito.jpg', 'https://iba-world.com/fernandito/', 'Pour the Fernet Branca into a double old fashioned glass with ice, fill the glass up with Cola. Gently stir.', 'Fernandito', 'N/A', 9),
(28, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-09-French-75-scaled.jpg', 'https://iba-world.com/french-75/', 'Pour all the ingredients, except Champagne, into a shaker. Shake well and strain into a Champagne flute. Top up with Champagne. Stir gently.', 'French 75', 'N/A', 7),
(29, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-10-French-Connection-scaled.jpg', 'https://iba-world.com/french-connection/', 'Pour all ingredients directly into an old fashioned glass filled with ice cubes. Stir gently.', 'French Connection', 'N/A', 5);     
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(30, 'New Era Drinks', 'Squeeze oil from lemon peel onto the drink.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-08-French-Martini.jpg', 'https://iba-world.com/french-martini/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'French Martini', 'N/A', 6),
(31, 'The Unforgettables', 'Garnish with a lemon slice, optional lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-12-Gin-Fizz.jpg', 'https://iba-world.com/gin-fizz/', 'Shake all ingredients with ice except soda water. Pour into thin tall Tumbler glass , top with a splash soda water.', 'Gin Fizz', 'Serve without ice.', 10),
(32, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-11-Golden-Dream-scaled.jpg', 'https://iba-world.com/golden-dream/', 'Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.', 'Golden Dream', 'N/A', 5),
(33, 'Contemporary Classics', 'Mint leaf (optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-12-Grasshopper-scaled.jpg', 'https://iba-world.com/grasshopper/', 'Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.', 'Grasshopper', 'N/A', 3),
(34, 'The Unforgettables', 'Orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-13-Hanky-Panky.jpg', 'https://iba-world.com/hanky-panky/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass.', 'Hanky Panky', 'N/A', 5),
(35, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-13-Hemingway-Special-scaled.jpg', 'https://iba-world.com/hemingway-special/', 'Pour all ingredients into a shaker with ice. Shake well and strain into a large cocktail glass.', 'Hemingway Special', 'N/A', 4),
(36, 'Contemporary Classics', 'Garnish with a rind of one lemon spiral.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-14-Horse_s-Neck-scaled.jpg', 'https://iba-world.com/horses-neck/', 'Pour Cognac and ginger ale directly into a highball glass with ice cubes. Stir gently. If preferred, add dashes of Angostura Bitter.', 'Horse''s Neck', 'N/A', 4),
(37, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-09-Illegal.jpg', 'https://iba-world.com/illegal/', 'Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled cocktail glass, or "on the rocks" in a traditional clay or terracotta mug.', 'Illegal', 'N/A', 1),
(38, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-15-Irish-Coffee-scaled.jpg', 'https://iba-world.com/irish-coffee/', 'Warm black coffee is poured into a pre-heated Irish coffee glass. Whiskey and at least one teaspoon of sugar is added and stirred until dissolved. Fresh thick chilled cream is carefully poured over the back of a spoon held just above the surface of the coffee. The layer of cream will float on the coffee without mixing. Plain sugar can be replaced with sugar syrup.', 'Irish Coffee', 'N/A', 9),
(39, 'The Unforgettables', 'Garnish with a lemon slice and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-14-John-Colins.jpg', 'https://iba-world.com/john-collins/', 'Pour all ingredients directly into a highball filled with ice. Stir gently.', 'John Collins', U&'Use \2018Old Tom'' Gin for Tom Collins.', 10),
(40, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-16-Kir-scaled.jpg', 'https://iba-world.com/kir/', 'Pour Creme de Cassis into glass, top up with white wine.', 'KIR', 'KIR Royal - Use Champagne instead of white wine.', 4),
(41, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-15-Last-World.jpg', 'https://iba-world.com/last-word/', 'Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.', 'Last word', 'N/A', 3);             
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(42, 'New Era Drinks', 'Garnish with sugar rim around the glass.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-10-Lemon-Drop-Martini.jpg', 'https://iba-world.com/lemon-drop-martini/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Lemon drop Martini', 'N/A', 5),
(43, 'Contemporary Classics', 'Lemon Slice (Optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-17-Long-Island-Iced-Tea-scaled.jpg', 'https://iba-world.com/long-island-ice-tea/', 'Add all ingredients into a highball glass filled with ice. Stir gently.', 'Long Island Ice Tea', 'N/A', 3),
(44, 'Contemporary Classics', 'Garnish with pineapple spear, mint leaves, and lime peel.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-18-Mai-Tai-scaled.jpg', 'https://iba-world.com/mai-tai/', 'Add all ingredients into a shaker with ice. Shake and pour into a double rocks glass or a highball glass.', 'Mai-Tai', 'The Martinique molasses rum used by Trader Vic was not an Agricole rum but a type of "rummy" from molasses.', 1),
(45, 'The Unforgettables', 'Garnish with a cocktail cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-16-Manhattan.jpg', 'https://iba-world.com/manhattan/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Manhattan', 'N/A', 6),
(46, 'Contemporary Classics', 'Half salt rim (Optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-19-Margarita-1-scaled.jpg', 'https://iba-world.com/margarita/', 'Add all ingredients into a shaker with ice. Shake and strain into a chilled cocktail glass.', 'Margarita', 'N/A', 5),
(47, 'The Unforgettables', 'Lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-17-Martinez.jpg', 'https://iba-world.com/martinez/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Martinez', 'N/A', 4),
(48, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-18-Mary-Pickford.jpg', 'https://iba-world.com/mary-pickford/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Mary Pickford', 'N/A', 5),
(49, 'Contemporary Classics', 'Garnish with an orange twist (optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-20-Mimosa-scaled.jpg', 'https://iba-world.com/mimosa/', 'Pour orange juice into a flute glass and gently pour the sparkling wine. Stir gently.', 'Mimosa', 'Also known as Buck''s Fizz.', 10),
(50, 'Contemporary Classics', 'Garnish with a mint sprig.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-21-Mint-Julep-scaled.jpg', 'https://iba-world.com/mint-julep/', 'In Julep Stainless Steel Cup gently muddle the mint with sugar and water. Fill the glass with cracked ice, add the Bourbon and stir well until the cup frosts.', 'Mint Julep', 'N/A', 9),
(51, 'Contemporary Classics', 'Garnish with sprigs of mint and slice of lime.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-22-Mojito-scaled.jpg', 'https://iba-world.com/mojito/', 'Mix mint springs with sugar and lime juice. Add splash of soda water and fill the glass with ice. Pour the rum and top with soda water. Light stir to involve all ingredients.', 'Mojito', 'N/A', 10),
(52, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-19-Monkey-Gland.jpg', 'https://iba-world.com/monkey-gland/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Monkey Gland', 'N/A', 5),
(53, 'Contemporary Classics', 'Garnish with a lime slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-23-Moscow-Mule-scaled.jpg', 'https://iba-world.com/moscow-mule/', 'In a Mule Cup or rocks glass, combine the vodka and ginger beer. Add lime juice and gently stir to involve all ingredients.', 'Moscow Mule', 'N/A', 8),
(54, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-11-Naked-and-Famous.jpg', 'https://iba-world.com/naked-and-famous/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Naked and Famous', 'N/A', 2);      
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(55, 'The Unforgettables', 'Garnish with a half orange slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-20-Negroni.jpg', 'https://iba-world.com/negroni/', 'Pour all ingredients directly into a chilled old fashioned glass filled with ice, Stir gently.', 'Negroni', 'N/A', 7),
(56, 'New Era Drinks', 'Garnish with lemon or orange zest with cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-12-NewYorkSour.jpg', 'https://iba-world.com/new-york-sour/', 'Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled rocks glass filled with ice. Float the wine on top.', 'New York Sour', 'N/A', 8),
(57, 'New Era Drinks', 'Garnish with mint springs.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-13-Old-Cuban.jpg', 'https://iba-world.com/old-cuban/', 'Pour all ingredients into cocktail shaker except the wine, shake well with ice, strain into chilled elegant cocktail glass. Top up with the sparkling wine.', 'Old Cuban', 'N/A', 7),
(58, 'The Unforgettables', 'Garnish with an orange slice or zest, and a cocktail cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-21-Old-Fashioned.jpg', 'https://iba-world.com/old-fashioned/', 'Place sugar cube in old fashioned glass and saturate with bitter, add few dashes of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey. Stir gently.', 'Old Fashioned', 'N/A', 9),
(59, 'New Era Drinks', 'Garnish with a slice of lime.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-14-Paloma.jpg', 'https://iba-world.com/paloma/', 'Poor the tequila into a highball glass, squeeze the lime juice. Add ice and salt, fill up pink grapefruit soda. Stir gently.', 'Paloma', 'N/A', 9),
(60, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-15-Paper-Plane.jpg', 'https://iba-world.com/paper-plane/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Paper Plane', 'N/A', 5),
(61, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-22-Paradise.jpg', 'https://iba-world.com/paradise/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Paradise', 'N/A', 6),
(62, 'New Era Drinks', 'Garnish with candied ginger.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-16-Penicillin.jpg', 'https://iba-world.com/penicillin/', 'Muddle fresh ginger in a shaker and add the remaining ingredients, except for the Islay single malt whiskey. Fill the shaker with ice and shake. Double-strain into a chilled old fashioned glass with ice. Float the single malt whisky on top.', 'Penicillin', 'N/A', 4),
(63, 'Contemporary Classics', 'Garnish with a slice of pineapple with a cocktail cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-24-Pina-Colada-scaled.jpg', 'https://iba-world.com/pina-colada/', 'Blend all the ingredients with ice in an electric blender, pour into a large glass, and serve with straws.', 'Pina Colada', 'Historically a few drops of fresh lime juice were added to taste. 4 slices of fresh pineapple can be used instead of juice.', 8),
(64, 'Contemporary Classics', 'Few dashes of Amargo bitters on top as an aromatic garnish.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-25-Pisco-Sour-scaled.jpg', 'https://iba-world.com/pisco-sour/', 'Add all ingredients into a shaker with ice. Shake and strain into a chilled goblet glass.', 'Pisco Sour', 'N/A', 6),
(65, 'The Unforgettables', 'Garnish with orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-23-Planters-Punch.jpg', 'https://iba-world.com/planters-punch/', 'Pour all ingredients directly in a small tumbler or a typical terracotta glass.', 'Planter''s Punch', 'Add dilution up to taste, it can be given by water, ice or fresh juices.', 4),
(66, 'The Unforgettables', 'Sprinkle with fresh ground nutmeg.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-24-Porto-Flip.jpg', 'https://iba-world.com/porto-flip/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Porto Flip', 'N/A', 5);        
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(67, 'The Unforgettables', 'N/A', U&'The drink was invented by Henry Ramos in 1888, at his bar Meyer''s Table d''H\00f4tel Internationale in New Orleans. The Ramos Fizz was originally shaken for 12 minutes by a crew of 30 bartenders who passed the shaker from one to another.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-25-Ramos-Fizz.jpg', 'https://iba-world.com/ramos-fizz/', 'Pour all ingredients except soda water in a cocktail shaker with ice, Shake for two minutes, double strain in a glass, pour the drink back in the shaker, and hard shake without ice for one minute. Strain into a highball glass, top up with soda.', 'Ramos Fizz', 'N/A', 6),
(68, 'New Era Drinks', 'Garnish with blackberries and optionally a lemon slice as well.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-17-Russian-Spring-Punch-1.jpg', 'https://iba-world.com/russian-spring-punch/', 'Pour all ingredients into a cocktail shaker except the sparkling wine, shake well with ice, strain into a chilled tall tumbler glass filled with ice, and top up with sparkling wine.', 'Russian Spring Punch', 'N/A', 5),
(69, 'The Unforgettables', 'Garnish with lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-26-Rusty-Nail.jpg', 'https://iba-world.com/rusty-nail/', 'Pour all ingredients directly into an old fashioned glass filled with ice. Stir gently.', 'Rusty Nail', 'N/A', 5),
(70, 'The Unforgettables', 'Garnish with lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-27-Sazerac.jpg', 'https://iba-world.com/sazerac/', 'Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice in a mixing glass. Discard the ice and any excess absinthe from the prepared glass, strain the mixed drink into the glass.', 'Sazerac', 'The original recipe changed after the American Civil War, Rye Whiskey substituted Cognac as it became hard to obtain.', 3),
(71, 'Contemporary Classics', 'Garnish with orange zest and cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-26-Sea-Breeze-scaled.jpg', 'https://iba-world.com/sea-breeze/', 'Build all ingredients in a highball glass filled with ice.', 'Sea Breeze', 'N/A', 4),
(72, 'Contemporary Classics', 'Garnish with a half orange slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-27-Sex-On-The-Beach-scaled.jpg', 'https://iba-world.com/sex-on-the-beach/', 'Build all ingredients in a highball glass filled with ice.', 'Sex on the Beach', 'N/A', 4),
(73, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-28-Side-Car-1.jpg', 'https://iba-world.com/sidecar/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Sidecar', 'N/A', 5),
(74, 'Contemporary Classics', 'Garnish with pineapple and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-28-Singapore-Sling-scaled.jpg', 'https://iba-world.com/singapore-sling/', 'Pour all ingredients into a cocktail shaker filled with ice cubes. Shake well. Strain into Hurricane glass.', 'Singapore Sling', 'N/A', 1),
(75, 'New Era Drinks', 'Garnish with mint springs.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-18-South-Side-1.jpg', 'https://iba-world.com/southside/', 'Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.', 'Southside', 'If egg white is used shake vigorously.', 10),
(76, 'New Era Drinks', 'Garnish with a red chili pepper.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-19-Spicy-Fifty-1.jpg', 'https://iba-world.com/spicy-fifty/', 'Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.', 'Spicy Fifty', 'N/A', 1),
(77, 'New Era Drinks', 'Garnish with a slice of orange.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-20-Spritz_ok.jpg', 'https://iba-world.com/spritz/', 'Build all ingredients into a wine glass filled with ice. Stir gently.', 'Spritz', 'There are other versions of the Spritz that use Campari, Cynar or Select instead of Aperol.', 9); 
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(78, 'The Unforgettables', 'Optional mint leave.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-29-Stinger.jpg', 'https://iba-world.com/stinger/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Stinger', 'N/A', 2),
(79, 'New Era Drinks', 'Garnish with mint springs and optionally an orange slice as well.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-21-Suffering-Bastard.jpg', 'https://iba-world.com/suffering-bastard/', 'Pour all ingredients into a cocktail shaker except the ginger beer, shake well with ice, Pour unstrained into a Collins glass or in the original Suffering Bastard mug and top up with ginger beer.', 'Suffering Bastard', 'N/A', 5),
(80, 'Contemporary Classics', 'Garnish with half orange slice or an orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-29-Tequila-Sunrise-scaled.jpg', 'https://iba-world.com/tequila-sunrise/', 'Pour tequila and orange juice directly into highball glass filled with ice cubes. Add the grenadine syrup to create chromatic effect (sunrise), do not stir.', 'Tequila Sunrise', 'N/A', 5),
(81, 'New Era Drinks', 'Garnish with a slice of orange.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-22-Tipperary.jpg', 'https://iba-world.com/tipperary/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Tipperary', 'N/A', 5),
(82, 'New Era Drinks', 'Garnish with a lime slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-23-Tommy-Margarita.jpg', 'https://iba-world.com/tommys-margarita/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled rocks glass filled with ice.', 'Tommy''s Margarita', 'N/A', 4),
(83, 'The Unforgettables', 'Garnish with cherry and lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-30-Tuxedo.jpg', 'https://iba-world.com/tuxedo/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Tuxedo', 'N/A', 3),
(84, 'New Era Drinks', 'Garnish with lemon zest and white grapes.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-26-VE.N.TO_-1.jpg', 'https://iba-world.com/ve-n-to/', 'Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled small tumbler glass filled with ice.', 'VE.N.TO', 'If desired water can be replaced by chamomile infusion in the honey mix.', 3),
(85, 'Contemporary Classics', 'Lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-30-Vesper-scaled.jpg', 'https://iba-world.com/vesper/', 'Pour all ingredients into a cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.', 'Vesper', 'N/A', 5),
(86, 'The Unforgettables', 'Garnish with orange zest and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-31-Vieus-Carre.jpg', 'https://iba-world.com/vieux-carre/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Vieux Carre', 'N/A', 2),
(87, 'The Unforgettables', 'Garnish with a half orange slice and maraschino cherry, optionally use orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-32-Whiskey-Sour.jpg', 'https://iba-world.com/whiskey-sour/', 'Pour all ingredients into a cocktail shaker filled with ice. Shake well. Strain into cobbler glass. If served "On the rocks", strain ingredients into an old fashioned glass filled with ice.', 'Whiskey Sour', 'If egg white is used shake little harder to release and incorporate the foam from the egg white.', 10),
(88, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-33-White-Lady.jpg', 'https://iba-world.com/white-lady/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'White Lady', 'N/A', 7),
(89, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-25-Yellow-Bird.jpg', 'https://iba-world.com/yellow-bird/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Yellow Bird', 'N/A', 5);               
INSERT INTO "PUBLIC"."COCKTAIL" VALUES
(90, 'Contemporary Classics', 'Garnish with mint leaves.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-31-Zombie-scaled.jpg', 'https://iba-world.com/zombie/', 'Add all ingredients into an electric blender with 170 grams of cracked ice. With pulse bottom blend for a few seconds. Serve in a tall tumbler glass.', 'Zombie', 'Donn''s Mix: 2 parts of fresh yellow grapefruit and 1 part of cinnamon syrup.', 2);            
CREATE MEMORY TABLE "PUBLIC"."COMPLETE_COCKTAIL"(
    "ID" INTEGER NOT NULL,
    "CATEGORY" CHARACTER VARYING(255),
    "GARNISH" CHARACTER VARYING(255),
    "HISTORY" CHARACTER VARYING,
    "IMAGEURL" CHARACTER VARYING(255),
    "INGREDIENTS_AND_QUANTITIES" CHARACTER VARYING,
    "LINK" CHARACTER VARYING(255),
    "METHOD" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255),
    "NOTE" CHARACTER VARYING(255),
    "SIMOXRATE" INTEGER
);         
ALTER TABLE "PUBLIC"."COMPLETE_COCKTAIL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");            
-- 90 +/- SELECT COUNT(*) FROM PUBLIC.COMPLETE_COCKTAIL;      
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(1, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-24-Trinidad-Sour.jpg', 'Angostura Bitters - 45 ml, Orgeat Syrup - 30 ml, Fresh Lemon Juice - 22.5 ml, Rye Whiskey - 15 ml', 'https://iba-world.com/trinidad-sour/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Trinidad Sour', 'N/A', 3),
(2, 'The Unforgettables', 'Sprinkle fresh ground nutmeg on top.', 'The Alexander cocktail was born in London in 1922 by Hery Mc Elhone, at Ciro''s Club in honor of a famous bride, at the beginning it was called Panama, Gin was used instead of Cognac and light cocoa cream instead of dark. Throughout its history, Alexander has given rise to many other variations: 1) Grasshopper: This variant is also part of the Iba list and involves the use of creme de menthe verde instead of cognac. 2) Alexandra: Use the light cocoa cream instead of the dark one and replace the nutmeg with cocoa. 3) Alexander''s Sister: Use creme de menthe instead of creme de cacao. 4) Alejandro: Replace cognac with rum.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-01-Alexander.jpg', 'Cognac - 30 ml, Creme de Cacao (Brown) - 30 ml, Fresh Cream - 30 ml', 'https://iba-world.com/alexander/', 'Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.', 'Alexander', 'N/A', 3),
(3, 'The Unforgettables', 'Garnish with half orange slice and a lemon zest.', 'The story of the Americano dates back to the second half of the 1800s in Gaspare Campari''s bar in Milan. Over the years the cocktail acquires notoriety thanks to some homages from the world of cinema, including James Bond (007 Casino Royale) whose favorite cocktail was, precisely, the Americano. The nickname "American" was born when Primo Carnera, a giant Italian boxer, became world heavyweight champion at Madison Square Garden in New York.  When Carnera returned to Italy with the title, he was greeted with this very Italian cocktail which, for the occasion, was called "Americano". The Americano entered the IBA Cocktail List only in 1987 but, in reality, it was a cocktail that spread all over Italy during the 1930s.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-02-Americano.jpg', 'Bitter Campari - 30 ml, Sweet Red Vermouth - 30 ml, Soda Water - A splash', 'https://iba-world.com/americano/', 'Mix the ingredients directly in an old fashioned glass filled with ice cubes. Add a splash of Soda Water. Stir gently.', 'Americano', 'N/A', 6),
(4, 'The Unforgettables', 'N/A', 'Although the origin of the cocktail is not known, the main hypotheses assume that it was born in the twenties of the twentieth century in France: this thesis would prove the presence of calvados, a liqueur commonly used in France and, in particular, in that period, as an epidemic of phylloxera in European vineyards had limited the production of brandy. On this basis, one of the most frequent hypotheses has it that the cocktail was created by Harry MacElhone, founder of Harry''s New York Bar in Paris on July 19, 1919, in honor of the celebrations for the victory of the First World War. The first reliable evidence, however, dates back to 1930 when Harry Craddock included the Angel Face among the recipes of his book "Savoy cocktail book". Some sources indicate that the name derives from that of an American gangster active during Prohibition; less likely the dedication to Rick Blaine, the protagonist of Casablanca played by Humphrey Bogart, as the film follows the first testimonies (1942).', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-03-Angel-Face.jpg', 'Gin - 30 ml, Apricot Brandy - 30 ml, Calvados - 30 ml', 'https://iba-world.com/angel-face/', 'Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.', 'Angel Face', 'N/A', 3),
(5, 'The Unforgettables', 'Optional Maraschino Cherry.', U&'Aviation was created in New York at the Walkick hotel by the head bartender Hugo Ensslin while he was writing his book "Recipes for Mixed Drinks" (1916) one of the last cocktail books published before the start of American Prohibition. Lately David Wondrich found the aviation recipe in a 1911 magazine, so the recipe is thought to have been born earlier then 1916. In his book Ensslin also indicates the type of Gin to be used \2018El Bart Gin "and the recipe is made up in addition to gin, with lemon juice, maraschino Luxardo and Creme di Violette. The recipe is found again in Harry Craddock''s 1930 Savoy Cocktail Book but without the Creme de Violette, this probably due to the difficulty of finding the violet cream during the post-war period In the 1960s it was still unavailable and therefore, simply, the basic ingredient of the Aviation cocktail was discontinued and the bartenders definitively gave up the characteristic blue color of the drink. The IBA proposes it today in its original version with the creme de violette which is now on the market again. This fragrant ingredient not only gave the mix a sweetly floral taste, but also gave it a beautiful sky blue color.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-04-Aviation.jpg', 'Gin - 45 ml, Maraschino Luxardo - 15 ml, Fresh Lemon Juice - 15 ml, Creme de Violette - 1 Bar Spoon', 'https://iba-world.com/692/', 'Add all ingredients into a cocktail shaker. Shake with cracked ice and strain into a chilled cocktail glass.', 'Aviation', 'N/A', 4);   
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(6, 'New Era Drinks', 'Pineapple and Cherry, optional mint sprig for additional aroma.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-01-Barracuda.jpg', 'Gold Rum - 45 ml, Galliano - 15 ml, Fresh Pineapple Juice - 60 ml, Fresh Lime Juice - 1 dash, Prosecco - Top up', 'https://iba-world.com/barracuda/', 'Pour all ingredients into cocktail shaker except the Prosecco, shake well with ice, strain into chilled highball glass filled with ice and top up with Prosecco.', 'Barracuda', 'N/A', 4),
(7, 'New Era Drinks', 'Optionally garnish with a lemon or orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-03-Bees-Knees.jpg', 'Dry Gin - 52.5 ml, Honey Syrup - 2 teaspoons, Fresh Lemon Juice - 22.5 ml, Fresh Orange Juice - 22.5 ml', 'https://iba-world.com/bees-knees/', 'Stir honey with lemon and orange juices until it dissolves, add gin and shake with ice. Strain into a chilled cocktail glass.', 'Bee''s Knees', 'N/A', 10),
(8, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-01-Bellini-scaled.jpg', 'Prosecco - 100 ml, White Peach Puree - 50 ml', 'https://iba-world.com/bellini/', 'Pour peach puree into the mixing glass with ice, add the Prosecco wine. Stir gently and pour in a chilled flute glass.', 'Bellini', 'Puccini - Fresh Mandarin Orange Juice; Rossini - Fresh Strawberry Puree; Tintoretto - Fresh Pomegranate Juice.', 5),
(9, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-05-Between-The-Sheets.jpg', 'White Rum - 30 ml, Cognac - 30 ml, Triple Sec - 30 ml, Fresh Lemon Juice - 20 ml', 'https://iba-world.com/between-the-sheets/', 'Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.', 'Between the Sheets', 'N/A', 3),
(10, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-02-Black-Russian-scaled.jpg', 'Vodka - 50 ml, Coffee Liqueur - 20 ml', 'https://iba-world.com/black-russian/', 'Pour the ingredients into the old fashioned glass filled with ice cubes. Stir gently.', 'Black Russian', 'White Russian - Float fresh cream on the top and stir in slowly.', 8),
(11, 'Contemporary Classics', 'Celery, Lemon Wedge (Optional)', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-03-Bloody-Marry-scaled.jpg', 'Vodka - 45 ml, Tomato Juice - 90 ml, Fresh Lemon Juice - 15 ml, Worcestershire Sauce - 2 dashes, Tabasco - Up to taste, Celery Salt - Up to taste, Pepper  - Up to taste', 'https://iba-world.com/bloody-mary/', 'Stir gently all the ingredients in a mixing glass with ice, pour into rocks glass.', 'Bloody Mary', 'If requested served with ice, pour into highball glass.', 5),
(12, 'The Unforgettables', 'Garnish with orange zest, optionally a lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-06-Boulevardier.jpg', 'Bourbon or Rye Whiskey - 45 ml, Bitter Campari - 30 ml, Sweet Red Vermouth - 30 ml', 'https://iba-world.com/boulevardier/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Boulevardier', 'N/A', 5),
(13, 'New Era Drinks', 'Garnish optionally with a lemon slice and blackberries.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-02-Bramble.jpg', 'Gin - 50 ml, Fresh Lemon Juice - 25 ml, Sugar Syrup - 12,5 ml, Creme de Mure - 15 ml', 'https://iba-world.com/bramble/', 'Pour all ingredients into a cocktail shaker except the Creme de Mure, shake well with ice, strain into chilled old fashioned glass filled with crushed ice, then pour the blackberry liqueur (Creme de Mure) over the top of the drink, in a circular motion.', 'Bramble', 'N/A', 6),
(14, 'The Unforgettables', 'Rub a slice of orange (or lemon) around the rim of the glass and dip it in pulverized white sugar, so that the sugar will adhere to the edge of the glass. Carefully curling place the orange/lemon peel around the inside of the glass.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-07-Brandy-Crusta.jpg', 'Brandy - 52,5 ml, Maraschino Luxardo - 7,5 ml, Curacao - 1 Bar Spoon, Fresh Lemon Juice - 15 ml, Simple Syrup - 1 Bar Spoon, Aromatic Bitters - 2 Dashes', 'https://iba-world.com/brandy-crusta/', 'Mix together all ingredients with ice cubes in a mixing glass and strain into prepared slim cocktail glass.', 'Brandy Crusta', 'N/A', 1);         
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(15, 'New Era Drinks', 'Lime wedge.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-04-Cachanchara.jpg', 'Cuban Aguardiente - 60 ml, Fresh Lime Juice - 15 ml, Raw Honey - 15 ml, Water - 50 ml', 'https://iba-world.com/cachanchara/', 'Mix honey with water and lime juice and spread the mixture on the bottom and sides of the glass. Add cracked ice, and then the rum. End by energetically stirring from bottom to top.', 'Canchanchara', 'N/A', 7),
(16, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-04-Caipirinha-scaled.jpg', U&'Cacha\00e7a - 60 ml, Lime  - 1 (cut into small wedges), White Cane Sugar - 4 Teaspoons', 'https://iba-world.com/caipirinha/', U&'Place lime and sugar into a double old fashioned glass and muddle gently. Fill the glass with cracked ice and add Cacha\00e7a. Stir gently to involve ingredients.', 'Caipirinha', U&'Caipiroska - Instead of Cacha\00e7a use Vodka;', 6),
(17, 'The Unforgettables', 'Garnish with lemon zest and a maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-08-Casino.jpg', 'Old Tom Gin - 40 ml, Maraschino Luxardo - 10 ml, Fresh Lemon Juice - 10 ml, Orange Bitters - 2 Dashes', 'https://iba-world.com/casino/', 'Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled rocks glass with ice.', 'Casino', 'N/A', 5),
(18, 'Contemporary Classics', 'Garnish with orange zest and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-05-Champagne-Cocktail-scaled.jpg', 'Chilled Champagne - 90 ml, Cognac - 10 ml, Angostura Bitters - 2 dashes, Grand Marnier - Few drops (Optional), Sugar Cube - 1', 'https://iba-world.com/champagne-cocktail/', 'Place the sugar cube with 2 dashes of bitters in a large Champagne glass, add the cognac. Pour gently chilled Champagne.', 'Champagne Cocktail', 'N/A', 2),
(19, 'The Unforgettables', 'Fresh raspberries.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-09-Clover-Club.jpg', 'Gin - 45 ml, Raspberry Syrup - 15 ml, Fresh Lemon Juice - 15 ml, Egg White - Few Drops', 'https://iba-world.com/clover-club/', 'Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled cocktail glass.', 'Clover Club', 'N/A', 7),
(20, 'Contemporary Classics', 'Garnish with orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-07-Corpse-Reviver2-scaled.jpg', 'Gin - 30 ml, Cointreau - 30 ml, Lillet Blanc - 30 ml, Fresh Lemon Juice - 30 ml, Absinthe - 1 dash', 'https://iba-world.com/corpse-reviver-2/', 'Pour all ingredients into shaker with ice. Shake well and strain in chilled cocktail glass.', 'Corpse Reviver #2', 'N/A', 2),
(21, 'Contemporary Classics', 'Garnish with a lemon twist.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-06-Cosmopolitan-scaled.jpg', 'Vodka Citron - 40 ml, Cointreau - 15 ml, Fresh Lime Juice - 15 ml, Cranberry Juice - 30 ml', 'https://iba-world.com/cosmopolitan/', 'Add all ingredients into a cocktail shaker filled with ice. Shake well and strain into a large cocktail glass.', 'Cosmopolitan', 'N/A', 2),
(22, 'Contemporary Classics', 'Garnish with lime wedge.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-08-Cuba-Libre-scaled.jpg', 'White Rum - 50 ml, Coca Cola - 120ml, Fresh Lime Juice - 10 ml', 'https://iba-world.com/cuba-libre/', 'Build all ingredients in a highball glass filled with ice.', 'Cuba Libre', 'N/A', 10),
(23, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-10-Daiquiri.jpg', 'White Cuban Ron (Rum) - 60 ml, Fresh Lime Juice - 20 ml, Superfine Sugar - 2 Bar Spoons', 'https://iba-world.com/daiquiri/', 'In a cocktail shaker add all ingredients. Stir well to dissolve the sugar. Add ice and shake. Strain into chilled cocktail glass.', 'Daiquiri', 'N/A', 10),
(24, 'New Era Drinks', 'Garnish with a lime wedge or slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-05-DarkNStormy.jpg', 'Goslings Rum - 60 ml, Ginger Beer - 100 ml', 'https://iba-world.com/dark-n-stormy/', 'In a highball glass filled with ice pour the ginger beer and top floating with the Rum.', U&'Dark \2018n'' stormy', 'N/A', 7);  
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(25, 'The Unforgettables', 'Squeeze oil from lemon peel onto the drink, or garnish with green olives if requested.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-11-Dry-Martini.jpg', 'Gin - 60 ml, Dry Vermouth - 10 ml', 'https://iba-world.com/dry-martini/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Dry Martini', 'N/A', 7),
(26, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-06-Espresso-Martini.jpg', U&'Vodka - 50 ml, Kahl\00faa - 30 ml, Sugar Syrup - 10 ml, Espresso (strong) - 1', 'https://iba-world.com/espresso-martini/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Espresso Martini', 'N/A', 8),
(27, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-07-Fernandito.jpg', 'Fernet Branca - 50 ml, Cola - Fill up', 'https://iba-world.com/fernandito/', 'Pour the Fernet Branca into a double old fashioned glass with ice, fill the glass up with Cola. Gently stir.', 'Fernandito', 'N/A', 9),
(28, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-09-French-75-scaled.jpg', 'Gin - 30 ml, Fresh Lemon Juice - 15 ml, Sugar Syrup - 15 ml, Champagne - 60 ml', 'https://iba-world.com/french-75/', 'Pour all the ingredients, except Champagne, into a shaker. Shake well and strain into a Champagne flute. Top up with Champagne. Stir gently.', 'French 75', 'N/A', 7),
(29, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-10-French-Connection-scaled.jpg', 'Cognac - 35 ml, Amaretto - 35 ml', 'https://iba-world.com/french-connection/', 'Pour all ingredients directly into an old fashioned glass filled with ice cubes. Stir gently.', 'French Connection', 'N/A', 5),
(30, 'New Era Drinks', 'Squeeze oil from lemon peel onto the drink.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-08-French-Martini.jpg', 'Vodka - 45 ml, Raspberry Liqueur - 15 ml, Fresh Pineapple Juice - 15 ml', 'https://iba-world.com/french-martini/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'French Martini', 'N/A', 6),
(31, 'The Unforgettables', 'Garnish with a lemon slice, optional lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-12-Gin-Fizz.jpg', 'Gin - 45 ml, Fresh Lemon Juice - 30 ml, Simple Syrup - 10 ml, Soda Water - Splash', 'https://iba-world.com/gin-fizz/', 'Shake all ingredients with ice except soda water. Pour into thin tall Tumbler glass , top with a splash soda water.', 'Gin Fizz', 'Serve without ice.', 10),
(32, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-11-Golden-Dream-scaled.jpg', 'Galliano - 20 ml, Triple Sec - 20 ml, Fresh Orange Juice - 20 ml, Fresh Cream - 10 ml', 'https://iba-world.com/golden-dream/', 'Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.', 'Golden Dream', 'N/A', 5),
(33, 'Contemporary Classics', 'Mint leaf (optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-12-Grasshopper-scaled.jpg', 'Creme de Cacao (White) - 20 ml, Creme de Menthe (Green) - 20 ml, Fresh Cream - 20 ml', 'https://iba-world.com/grasshopper/', 'Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.', 'Grasshopper', 'N/A', 3),
(34, 'The Unforgettables', 'Orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-13-Hanky-Panky.jpg', 'London Dry Gin - 45 ml, Sweet Red Vermouth - 45 ml, Fernet Branca - 7.5 ml', 'https://iba-world.com/hanky-panky/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass.', 'Hanky Panky', 'N/A', 5),
(35, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-13-Hemingway-Special-scaled.jpg', 'Rum - 60 ml, Grapefruit Juice - 40 ml, Maraschino Luxardo - 15 ml, Fresh Lime - 15 ml', 'https://iba-world.com/hemingway-special/', 'Pour all ingredients into a shaker with ice. Shake well and strain into a large cocktail glass.', 'Hemingway Special', 'N/A', 4);               
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(36, 'Contemporary Classics', 'Garnish with a rind of one lemon spiral.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-14-Horse_s-Neck-scaled.jpg', 'Cognac - 40 ml, Ginger Ale - 120 ml, Angostura Bitters - Dash (optional)', 'https://iba-world.com/horses-neck/', 'Pour Cognac and ginger ale directly into a highball glass with ice cubes. Stir gently. If preferred, add dashes of Angostura Bitter.', 'Horse''s Neck', 'N/A', 4),
(37, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-09-Illegal.jpg', 'Espadin Mezcal - 30 ml, Jamaica Overproof White Rum - 15 ml, Falernum - 15 ml, Maraschino Luxardo - 1 Bar Spoon, Fresh Lime Juice - 22.5 ml, Simple Syrup - 15 ml, Egg White - Few Drops (Optional)', 'https://iba-world.com/illegal/', 'Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled cocktail glass, or "on the rocks" in a traditional clay or terracotta mug.', 'Illegal', 'N/A', 1),
(38, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-15-Irish-Coffee-scaled.jpg', 'Irish Whiskey - 50 ml, Hot coffee - 120 ml, Fresh Cream - 50 ml (Chilled), Sugar - 1 teaspoon', 'https://iba-world.com/irish-coffee/', 'Warm black coffee is poured into a pre-heated Irish coffee glass. Whiskey and at least one teaspoon of sugar is added and stirred until dissolved. Fresh thick chilled cream is carefully poured over the back of a spoon held just above the surface of the coffee. The layer of cream will float on the coffee without mixing. Plain sugar can be replaced with sugar syrup.', 'Irish Coffee', 'N/A', 9),
(39, 'The Unforgettables', 'Garnish with a lemon slice and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-14-John-Colins.jpg', 'Gin - 45 ml, Fresh Lemon Juice - 30 ml, Simple Syrup - 15 ml, Soda Water - 60 ml', 'https://iba-world.com/john-collins/', 'Pour all ingredients directly into a highball filled with ice. Stir gently.', 'John Collins', U&'Use \2018Old Tom'' Gin for Tom Collins.', 10),
(40, 'Contemporary Classics', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-16-Kir-scaled.jpg', 'Dry White Wine - 90 ml, Creme de Cassis - 10 ml', 'https://iba-world.com/kir/', 'Pour Creme de Cassis into glass, top up with white wine.', 'KIR', 'KIR Royal - Use Champagne instead of white wine.', 4),
(41, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-15-Last-World.jpg', 'Gin - 22.5 ml, Green Chartreuse - 22.5 ml, Maraschino Luxardo - 22.5 ml, Fresh Lime Juice - 22.5 ml', 'https://iba-world.com/last-word/', 'Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.', 'Last word', 'N/A', 3),
(42, 'New Era Drinks', 'Garnish with sugar rim around the glass.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-10-Lemon-Drop-Martini.jpg', 'Vodka Citron  - 30 ml, Triple Sec - 20 ml, Fresh Lemon Juice - 15 ml', 'https://iba-world.com/lemon-drop-martini/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Lemon drop Martini', 'N/A', 5),
(43, 'Contemporary Classics', 'Lemon Slice (Optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-17-Long-Island-Iced-Tea-scaled.jpg', 'Vodka - 15 ml, Tequila - 15 ml, White Rum - 15 ml, Gin - 15 ml, Cointreau - 15 ml, Fresh Lemon Juice - 30 ml, Simple Syrup - 20 ml, Cola - Top up', 'https://iba-world.com/long-island-ice-tea/', 'Add all ingredients into a highball glass filled with ice. Stir gently.', 'Long Island Ice Tea', 'N/A', 3),
(44, 'Contemporary Classics', 'Garnish with pineapple spear, mint leaves, and lime peel.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-18-Mai-Tai-scaled.jpg', 'Amber Jamaican Rum - 30 ml, Martinique Molasses Rhum - 30 ml, Orange Curacao - 15 ml, Orgeat Syrup - 15 ml, Fresh Lime Juice - 30 ml, Simple Syrup - 7.5 ml', 'https://iba-world.com/mai-tai/', 'Add all ingredients into a shaker with ice. Shake and pour into a double rocks glass or a highball glass.', 'Mai-Tai', 'The Martinique molasses rum used by Trader Vic was not an Agricole rum but a type of "rummy" from molasses.', 1);               
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(45, 'The Unforgettables', 'Garnish with a cocktail cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-16-Manhattan.jpg', 'Rye Whiskey - 50 ml, Sweet Red Vermouth - 20 ml, Angostura Bitters - 1 dash', 'https://iba-world.com/manhattan/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Manhattan', 'N/A', 6),
(46, 'Contemporary Classics', 'Half salt rim (Optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-19-Margarita-1-scaled.jpg', 'Tequila 100% Agave - 50 ml, Triple Sec - 20 ml, Freshly Squeezed Lime Juice - 15 ml', 'https://iba-world.com/margarita/', 'Add all ingredients into a shaker with ice. Shake and strain into a chilled cocktail glass.', 'Margarita', 'N/A', 5),
(47, 'The Unforgettables', 'Lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-17-Martinez.jpg', 'London Dry Gin - 45 ml, Sweet Red Vermouth - 45 ml, Maraschino Liqueur - 1 Bar Spoon, Orange Bitters - 2 Dashes', 'https://iba-world.com/martinez/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Martinez', 'N/A', 4),
(48, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-18-Mary-Pickford.jpg', 'White Rum - 45 ml, Fresh Pineapple Juice - 45 ml, Maraschino Luxardo - 7.5 ml, Grenadine Syrup - 5 ml', 'https://iba-world.com/mary-pickford/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Mary Pickford', 'N/A', 5),
(49, 'Contemporary Classics', 'Garnish with an orange twist (optional).', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-20-Mimosa-scaled.jpg', 'Fresh Orange Juice - 75 ml, Prosecco - 75 ml', 'https://iba-world.com/mimosa/', 'Pour orange juice into a flute glass and gently pour the sparkling wine. Stir gently.', 'Mimosa', 'Also known as Buck''s Fizz.', 10),
(50, 'Contemporary Classics', 'Garnish with a mint sprig.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-21-Mint-Julep-scaled.jpg', 'Bourbon Whiskey - 60 ml, Fresh Mint sprigs - 4, Powdered Sugar - 1 tsp, Water - 2 tsp', 'https://iba-world.com/mint-julep/', 'In Julep Stainless Steel Cup gently muddle the mint with sugar and water. Fill the glass with cracked ice, add the Bourbon and stir well until the cup frosts.', 'Mint Julep', 'N/A', 9),
(51, 'Contemporary Classics', 'Garnish with sprigs of mint and slice of lime.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-22-Mojito-scaled.jpg', 'White Cuban Ron (Rum) - 45 ml, Fresh Lime Juice - 20 ml, Mint Sprigs - 6 pcs, White Cane Sugar - 2 tsp, Soda Water - Top up', 'https://iba-world.com/mojito/', 'Mix mint springs with sugar and lime juice. Add splash of soda water and fill the glass with ice. Pour the rum and top with soda water. Light stir to involve all ingredients.', 'Mojito', 'N/A', 10),
(52, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-19-Monkey-Gland.jpg', 'Dry Gin - 45 ml, Fresh Orange Juice - 45 ml, Absinthe - 1 Table Spoon, Grenadine Syrup - 1 Table Spoon', 'https://iba-world.com/monkey-gland/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Monkey Gland', 'N/A', 5),
(53, 'Contemporary Classics', 'Garnish with a lime slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-23-Moscow-Mule-scaled.jpg', 'Smirnoff Vodka - 45 ml, Ginger Beer - 120 ml, Fresh Lime Juice - 10 ml', 'https://iba-world.com/moscow-mule/', 'In a Mule Cup or rocks glass, combine the vodka and ginger beer. Add lime juice and gently stir to involve all ingredients.', 'Moscow Mule', 'N/A', 8),
(54, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-11-Naked-and-Famous.jpg', 'Mezcal - 22.5 ml, Yellow Chartreuse - 22.5 ml, Aperol - 22.5 ml, Fresh Lime Juice - 22.5 ml', 'https://iba-world.com/naked-and-famous/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Naked and Famous', 'N/A', 2);
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(55, 'The Unforgettables', 'Garnish with a half orange slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-20-Negroni.jpg', 'Gin - 30 ml, Bitter Campari - 30 ml, Sweet Red Vermouth - 30 ml', 'https://iba-world.com/negroni/', 'Pour all ingredients directly into a chilled old fashioned glass filled with ice, Stir gently.', 'Negroni', 'N/A', 7),
(56, 'New Era Drinks', 'Garnish with lemon or orange zest with cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-12-NewYorkSour.jpg', 'Bourbon or Rye Whiskey - 60 ml, Simple Syrup - 22.5 ml, Fresh Lemon Juice - 30 ml, Egg White - Few Drops, Red wine (Shiraz or Malbech) - 15 ml', 'https://iba-world.com/new-york-sour/', 'Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled rocks glass filled with ice. Float the wine on top.', 'New York Sour', 'N/A', 8),
(57, 'New Era Drinks', 'Garnish with mint springs.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-13-Old-Cuban.jpg', 'Mint Leaves - 6/8 pcs, Aged Rum - 45 ml, Fresh Lime Juice - 22.5 ml, Simple Syrup - 30 ml, Angostura Bitters - 2 Dashes, Brut Champagne or Prosecco - 60 ml', 'https://iba-world.com/old-cuban/', 'Pour all ingredients into cocktail shaker except the wine, shake well with ice, strain into chilled elegant cocktail glass. Top up with the sparkling wine.', 'Old Cuban', 'N/A', 7),
(58, 'The Unforgettables', 'Garnish with an orange slice or zest, and a cocktail cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-21-Old-Fashioned.jpg', 'Bourbon or Rye Whiskey - 45 ml, Sugar Cube - 1, Angostura Bitters - Few Dashes, Plain Water - Few Dashes', 'https://iba-world.com/old-fashioned/', 'Place sugar cube in old fashioned glass and saturate with bitter, add few dashes of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey. Stir gently.', 'Old Fashioned', 'N/A', 9),
(59, 'New Era Drinks', 'Garnish with a slice of lime.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-14-Paloma.jpg', '100% Agave Tequila - 50 ml, Fresh Lime - 5 ml, Salt - A pinch, Pink Grapefruit Soda - 100 ml', 'https://iba-world.com/paloma/', 'Poor the tequila into a highball glass, squeeze the lime juice. Add ice and salt, fill up pink grapefruit soda. Stir gently.', 'Paloma', 'N/A', 9),
(60, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-15-Paper-Plane.jpg', 'Bourbon Whiskey - 30 ml, Amaro Nonino - 30 ml, Aperol - 30 ml, Fresh Lemon Juice - 30 ml', 'https://iba-world.com/paper-plane/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Paper Plane', 'N/A', 5),
(61, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-22-Paradise.jpg', 'Gin - 30 ml, Apricot Brandy - 20 ml, Fresh Orange Juice - 15 ml', 'https://iba-world.com/paradise/', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Paradise', 'N/A', 6),
(62, 'New Era Drinks', 'Garnish with candied ginger.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-16-Penicillin.jpg', 'Blended Scotch Whisky - 60 ml, Lagavulin 16y Whisky - 7.5 ml, Fresh Lemon Juice - 22.5 ml, Honey Syrup - 22.5 ml, Sliced Fresh Ginger - 2-3 quarter size', 'https://iba-world.com/penicillin/', 'Muddle fresh ginger in a shaker and add the remaining ingredients, except for the Islay single malt whiskey. Fill the shaker with ice and shake. Double-strain into a chilled old fashioned glass with ice. Float the single malt whisky on top.', 'Penicillin', 'N/A', 4),
(63, 'Contemporary Classics', 'Garnish with a slice of pineapple with a cocktail cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-24-Pina-Colada-scaled.jpg', 'White Rum - 50 ml, Coconut Cream - 30 ml, Fresh Pineapple Juice - 50 ml', 'https://iba-world.com/pina-colada/', 'Blend all the ingredients with ice in an electric blender, pour into a large glass, and serve with straws.', 'Pina Colada', 'Historically a few drops of fresh lime juice were added to taste. 4 slices of fresh pineapple can be used instead of juice.', 8);             
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(64, 'Contemporary Classics', 'Few dashes of Amargo bitters on top as an aromatic garnish.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-25-Pisco-Sour-scaled.jpg', 'Pisco - 60 ml, Fresh Lemon Juice - 30 ml, Simple Syrup - 20 ml, Egg White - 1 Raw', 'https://iba-world.com/pisco-sour/', 'Add all ingredients into a shaker with ice. Shake and strain into a chilled goblet glass.', 'Pisco Sour', 'N/A', 6),
(65, 'The Unforgettables', 'Garnish with orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-23-Planters-Punch.jpg', 'Jamaican Rum - 45 ml, Lime Juice - 15 ml, Sugar Cane Juice - 30 ml', 'https://iba-world.com/planters-punch/', 'Pour all ingredients directly in a small tumbler or a typical terracotta glass.', 'Planter''s Punch', 'Add dilution up to taste, it can be given by water, ice or fresh juices.', 4),
(66, 'The Unforgettables', 'Sprinkle with fresh ground nutmeg.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-24-Porto-Flip.jpg', 'Brandy - 15 ml, Red Tawny Port Wine - 45 ml, Egg Yolk - 10 ml', 'https://iba-world.com/porto-flip/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Porto Flip', 'N/A', 5),
(67, 'The Unforgettables', 'N/A', U&'The drink was invented by Henry Ramos in 1888, at his bar Meyer''s Table d''H\00f4tel Internationale in New Orleans. The Ramos Fizz was originally shaken for 12 minutes by a crew of 30 bartenders who passed the shaker from one to another.', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-25-Ramos-Fizz.jpg', 'Gin - 45 ml, Fresh Lime Juice - 15 ml, Fresh Lemon Juice - 15 ml, Sugar Syrup - 30 ml, Cream - 60 ml, Egg White - 30ml, Orange Flower Water - 3 Dashes, Vanilla Extract - 2 Drops, Soda Water - Top up', 'https://iba-world.com/ramos-fizz/', 'Pour all ingredients except soda water in a cocktail shaker with ice, Shake for two minutes, double strain in a glass, pour the drink back in the shaker, and hard shake without ice for one minute. Strain into a highball glass, top up with soda.', 'Ramos Fizz', 'N/A', 6),
(68, 'New Era Drinks', 'Garnish with blackberries and optionally a lemon slice as well.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-17-Russian-Spring-Punch-1.jpg', 'Vodka - 25 ml, Fresh Lemon Juice - 25 ml, Creme de Cassis - 15 ml, Sugar Syrup - 10 ml, Sparkling wine - Top up', 'https://iba-world.com/russian-spring-punch/', 'Pour all ingredients into a cocktail shaker except the sparkling wine, shake well with ice, strain into a chilled tall tumbler glass filled with ice, and top up with sparkling wine.', 'Russian Spring Punch', 'N/A', 5),
(69, 'The Unforgettables', 'Garnish with lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-26-Rusty-Nail.jpg', 'Scotch Whisky - 45 ml, Drambuie - 25ml', 'https://iba-world.com/rusty-nail/', 'Pour all ingredients directly into an old fashioned glass filled with ice. Stir gently.', 'Rusty Nail', 'N/A', 5),
(70, 'The Unforgettables', 'Garnish with lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-27-Sazerac.jpg', U&'Cognac - 50 ml, Absinthe - 10 ml, Sugar Cube - 1, Peychaud\2019s Bitters - 2 Dashes', 'https://iba-world.com/sazerac/', 'Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice in a mixing glass. Discard the ice and any excess absinthe from the prepared glass, strain the mixed drink into the glass.', 'Sazerac', 'The original recipe changed after the American Civil War, Rye Whiskey substituted Cognac as it became hard to obtain.', 3),
(71, 'Contemporary Classics', 'Garnish with orange zest and cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-26-Sea-Breeze-scaled.jpg', 'Vodka - 40 ml, Cranberry Juice - 120 ml, Grapefruit Juice - 30 ml', 'https://iba-world.com/sea-breeze/', 'Build all ingredients in a highball glass filled with ice.', 'Sea Breeze', 'N/A', 4),
(72, 'Contemporary Classics', 'Garnish with a half orange slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-27-Sex-On-The-Beach-scaled.jpg', 'Vodka - 40 ml, Peach Schnapps - 20 ml, Fresh Orange Juice - 40 ml, Cranberry Juice - 40 ml', 'https://iba-world.com/sex-on-the-beach/', 'Build all ingredients in a highball glass filled with ice.', 'Sex on the Beach', 'N/A', 4);          
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(73, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-28-Side-Car-1.jpg', 'Cognac - 50 ml, Triple Sec - 20 ml, Fresh Lemon Juice - 20 ml', 'https://iba-world.com/sidecar/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'Sidecar', 'N/A', 5),
(74, 'Contemporary Classics', 'Garnish with pineapple and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-28-Singapore-Sling-scaled.jpg', U&'Gin - 30 ml, Cherry liqueur - 15 ml, Cointreau - 7.5 ml, DOM Be\00b4ne\00b4dictine - 7.5 ml, Fresh Pineapple Juice - 120 ml, Fresh Lime Juice - 15 ml, Grenadine Syrup - 10 ml, Angostura Bitters - A dash', 'https://iba-world.com/singapore-sling/', 'Pour all ingredients into a cocktail shaker filled with ice cubes. Shake well. Strain into Hurricane glass.', 'Singapore Sling', 'N/A', 1),
(75, 'New Era Drinks', 'Garnish with mint springs.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-18-South-Side-1.jpg', 'London Dry Gin - 60 ml, Fresh Lemon Juice - 30 ml, Simple Syrup - 15 ml, Mint Leaves - 5/6, Egg White - Few Drops (Optional)', 'https://iba-world.com/southside/', 'Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.', 'Southside', 'If egg white is used shake vigorously.', 10),
(76, 'New Era Drinks', 'Garnish with a red chili pepper.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-19-Spicy-Fifty-1.jpg', 'Vodka Vanilla - 50 ml, Elderflower Cordial - 15 ml, Fresh Lime Juice - 15 ml, Monin Honey Syrup - 10 ml, Red Chili Pepper - 2 thin Slices', 'https://iba-world.com/spicy-fifty/', 'Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.', 'Spicy Fifty', 'N/A', 1),
(77, 'New Era Drinks', 'Garnish with a slice of orange.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-20-Spritz_ok.jpg', 'Prosecco - 90 ml, Aperol - 60 ml, Soda Water - Splash', 'https://iba-world.com/spritz/', 'Build all ingredients into a wine glass filled with ice. Stir gently.', 'Spritz', 'There are other versions of the Spritz that use Campari, Cynar or Select instead of Aperol.', 9),
(78, 'The Unforgettables', 'Optional mint leave.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-29-Stinger.jpg', 'Cognac - 50 ml, White Creme de Menthe - 20 ml', 'https://iba-world.com/stinger/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Stinger', 'N/A', 2),
(79, 'New Era Drinks', 'Garnish with mint springs and optionally an orange slice as well.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-21-Suffering-Bastard.jpg', 'Cognac or Brandy - 30 ml, Gin - 30 ml, Fresh Lime Juice - 15 ml, Angostura Bitters - 2 Dashes, Ginger Beer - Top up', 'https://iba-world.com/suffering-bastard/', 'Pour all ingredients into a cocktail shaker except the ginger beer, shake well with ice, Pour unstrained into a Collins glass or in the original Suffering Bastard mug and top up with ginger beer.', 'Suffering Bastard', 'N/A', 5),
(80, 'Contemporary Classics', 'Garnish with half orange slice or an orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-29-Tequila-Sunrise-scaled.jpg', 'Tequila - 45ml, Fresh Orange Juice - 90 ml, Grenadine Syrup - 15 ml', 'https://iba-world.com/tequila-sunrise/', 'Pour tequila and orange juice directly into highball glass filled with ice cubes. Add the grenadine syrup to create chromatic effect (sunrise), do not stir.', 'Tequila Sunrise', 'N/A', 5),
(81, 'New Era Drinks', 'Garnish with a slice of orange.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-22-Tipperary.jpg', 'Irish Whiskey - 50 ml, Sweet Red Vermouth - 25 ml, Green Chartreuse - 15 ml, Angostura Bitters - 2 Dashes', 'https://iba-world.com/tipperary/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Tipperary', 'N/A', 5);       
INSERT INTO "PUBLIC"."COMPLETE_COCKTAIL" VALUES
(82, 'New Era Drinks', 'Garnish with a lime slice.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-23-Tommy-Margarita.jpg', 'Tequila Agave 100% Reposado - 60 ml, Fresh Lime Juice (Persiano) - 30 ml, Agave Syrup (1/2 Water + 1/2 Agave Nectar) - 30 ml', 'https://iba-world.com/tommys-margarita/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled rocks glass filled with ice.', 'Tommy''s Margarita', 'N/A', 4),
(83, 'The Unforgettables', 'Garnish with cherry and lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-30-Tuxedo.jpg', 'Old Tom Gin - 30 ml, Dry Vermouth - 30 ml, Maraschino Luxardo - 1/2 Bar Spoon, Absinthe - 1/4 Bar Spoon, Orange Bitters - 3 Dashes', 'https://iba-world.com/tuxedo/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.', 'Tuxedo', 'N/A', 3),
(84, 'New Era Drinks', 'Garnish with lemon zest and white grapes.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-26-VE.N.TO_-1.jpg', 'White Smooth Grappa - 45 ml, Fresh Lemon Juice - 22.5 ml, Honey mix (replace water with chamomile) - 15 ml, Chamomile cordial - 15 ml, Egg White - 10ml (Optional)', 'https://iba-world.com/ve-n-to/', 'Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled small tumbler glass filled with ice.', 'VE.N.TO', 'If desired water can be replaced by chamomile infusion in the honey mix.', 3),
(85, 'Contemporary Classics', 'Lemon zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-30-Vesper-scaled.jpg', 'Gin - 45 ml, Vodka - 15 ml, Lillet Blanc - 7.5 ml', 'https://iba-world.com/vesper/', 'Pour all ingredients into a cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.', 'Vesper', 'N/A', 5),
(86, 'The Unforgettables', 'Garnish with orange zest and maraschino cherry.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-31-Vieus-Carre.jpg', U&'Rye Whiskey - 30 ml, Cognac - 30 ml, Sweet Vermouth - 30 ml, Be\00b4ne\00b4dictine - 1 Bar Spoon, Peychaud\2019s Bitters - 2 Dashes', 'https://iba-world.com/vieux-carre/', 'Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.', 'Vieux Carre', 'N/A', 2),
(87, 'The Unforgettables', 'Garnish with a half orange slice and maraschino cherry, optionally use orange zest.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-32-Whiskey-Sour.jpg', 'Bourbon Whiskey - 45 ml, Fresh Lemon Juice - 25 ml, Sugar Syrup - 20 ml, Egg White (Optional) - 20 ml', 'https://iba-world.com/whiskey-sour/', 'Pour all ingredients into a cocktail shaker filled with ice. Shake well. Strain into cobbler glass. If served "On the rocks", strain ingredients into an old fashioned glass filled with ice.', 'Whiskey Sour', 'If egg white is used shake little harder to release and incorporate the foam from the egg white.', 10),
(88, 'The Unforgettables', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-TU-33-White-Lady.jpg', 'Gin - 40 ml, Triple Sec - 30 ml, Fresh Lemon Juice - 20 ml', 'https://iba-world.com/white-lady/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.', 'White Lady', 'N/A', 7),
(89, 'New Era Drinks', 'N/A', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-NE-25-Yellow-Bird.jpg', 'White Rum - 30 ml, Galliano - 15 ml, Triple Sec - 15 ml, Fresh Lime Juice - 15 ml', 'https://iba-world.com/yellow-bird/', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Yellow Bird', 'N/A', 5),
(90, 'Contemporary Classics', 'Garnish with mint leaves.', 'N/A', 'https://iba-world.com/wp-content/uploads/2021/02/IBA-CC-31-Zombie-scaled.jpg', U&'Jamaican dark rum - 45 ml, Gold Puerto Rican rum - 45 ml, Demerara Rum - 30 ml, Fresh Lime Juice - 20 ml, Falernum - 15 ml, Donn\2019s Mix - 15 ml, Grenadine Syrup - 1 tsp, Angostura Bitters - 1 dash, Pernod - 6 drops', 'https://iba-world.com/zombie/', 'Add all ingredients into an electric blender with 170 grams of cracked ice. With pulse bottom blend for a few seconds. Serve in a tall tumbler glass.', 'Zombie', 'Donn''s Mix: 2 parts of fresh yellow grapefruit and 1 part of cinnamon syrup.', 2);     
CREATE MEMORY TABLE "PUBLIC"."INGREDIENT"(
    "ID" INTEGER NOT NULL,
    "NAME" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."INGREDIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");   
-- 153 +/- SELECT COUNT(*) FROM PUBLIC.INGREDIENT;            
INSERT INTO "PUBLIC"."INGREDIENT" VALUES
(1, 'Angostura Bitters'),
(2, 'Orgeat Syrup'),
(3, 'Fresh Lemon Juice'),
(4, 'Rye Whiskey'),
(5, 'Cognac'),
(6, 'Creme de Cacao (Brown)'),
(7, 'Fresh Cream'),
(8, 'Bitter Campari'),
(9, 'Sweet Red Vermouth'),
(10, 'Soda Water'),
(11, 'Gin'),
(12, 'Apricot Brandy'),
(13, 'Calvados'),
(14, 'Maraschino Luxardo'),
(15, 'Creme de Violette'),
(16, 'Gold Rum'),
(17, 'Galliano'),
(18, 'Fresh Pineapple Juice'),
(19, 'Fresh Lime Juice'),
(20, 'Prosecco'),
(21, 'Dry Gin'),
(22, 'Honey Syrup'),
(23, 'Fresh Orange Juice'),
(24, 'White Peach Puree'),
(25, 'White Rum'),
(26, 'Triple Sec'),
(27, 'Vodka'),
(28, 'Coffee Liqueur'),
(29, 'Tomato Juice'),
(30, 'Worcestershire Sauce'),
(31, 'Tabasco'),
(32, 'Celery Salt'),
(33, 'Pepper '),
(34, 'Bourbon or Rye Whiskey'),
(35, 'Sugar Syrup'),
(36, 'Creme de Mure'),
(37, 'Brandy'),
(38, 'Curacao'),
(39, 'Simple Syrup'),
(40, 'Aromatic Bitters'),
(41, 'Cuban Aguardiente'),
(42, 'Raw Honey'),
(43, 'Water'),
(44, U&'Cacha\00e7a'),
(45, 'Lime '),
(46, 'White Cane Sugar'),
(47, 'Old Tom Gin'),
(48, 'Orange Bitters'),
(49, 'Chilled Champagne'),
(50, 'Grand Marnier'),
(51, 'Sugar Cube'),
(52, 'Raspberry Syrup'),
(53, 'Egg White'),
(54, 'Cointreau'),
(55, 'Lillet Blanc'),
(56, 'Absinthe'),
(57, 'Vodka Citron'),
(58, 'Cranberry Juice'),
(59, 'Coca Cola'),
(60, 'White Cuban Ron (Rum)'),
(61, 'Superfine Sugar'),
(62, 'Goslings Rum'),
(63, 'Ginger Beer'),
(64, 'Dry Vermouth'),
(65, U&'Kahl\00faa'),
(66, 'Espresso (strong)'),
(67, 'Fernet Branca'),
(68, 'Cola'),
(69, 'Champagne'),
(70, 'Amaretto'),
(71, 'Raspberry Liqueur'),
(72, 'Creme de Cacao (White)'),
(73, 'Creme de Menthe (Green)'),
(74, 'London Dry Gin'),
(75, 'Rum'),
(76, 'Grapefruit Juice'),
(77, 'Fresh Lime'),
(78, 'Ginger Ale'),
(79, 'Espadin Mezcal'),
(80, 'Jamaica Overproof White Rum'),
(81, 'Falernum'),
(82, 'Irish Whiskey'),
(83, 'Hot coffee'),
(84, 'Sugar'),
(85, 'Dry White Wine'),
(86, 'Creme de Cassis'),
(87, 'Green Chartreuse'),
(88, 'Vodka Citron '),
(89, 'Tequila'),
(90, 'Amber Jamaican Rum'),
(91, 'Martinique Molasses Rhum'),
(92, 'Orange Curacao'),
(93, 'Tequila 100% Agave'),
(94, 'Freshly Squeezed Lime Juice'),
(95, 'Maraschino Liqueur'),
(96, 'Grenadine Syrup'),
(97, 'Bourbon Whiskey'),
(98, 'Fresh Mint sprigs'),
(99, 'Powdered Sugar'),
(100, 'Mint Sprigs'),
(101, 'Smirnoff Vodka'),
(102, 'Mezcal'),
(103, 'Yellow Chartreuse'),
(104, 'Aperol'),
(105, 'Red wine (Shiraz or Malbech)'),
(106, 'Mint Leaves'),
(107, 'Aged Rum'),
(108, 'Brut Champagne or Prosecco'),
(109, 'Plain Water'),
(110, '100% Agave Tequila'),
(111, 'Salt'),
(112, 'Pink Grapefruit Soda'),
(113, 'Amaro Nonino'),
(114, 'Blended Scotch Whisky'),
(115, 'Lagavulin 16y Whisky'),
(116, 'Sliced Fresh Ginger'),
(117, 'Coconut Cream'),
(118, 'Pisco'),
(119, 'Jamaican Rum'),
(120, 'Lime Juice'),
(121, 'Sugar Cane Juice'),
(122, 'Red Tawny Port Wine'),
(123, 'Egg Yolk'),
(124, 'Cream'),
(125, 'Orange Flower Water'),
(126, 'Vanilla Extract'),
(127, 'Sparkling wine'),
(128, 'Scotch Whisky'),
(129, 'Drambuie'),
(130, U&'Peychaud\2019s Bitters'),
(131, 'Peach Schnapps'),
(132, 'Cherry liqueur'),
(133, U&'DOM Be\00b4ne\00b4dictine'),
(134, 'Vodka Vanilla'),
(135, 'Elderflower Cordial'),
(136, 'Monin Honey Syrup'),
(137, 'Red Chili Pepper'),
(138, 'White Creme de Menthe'),
(139, 'Cognac or Brandy'),
(140, 'Tequila Agave 100% Reposado'),
(141, 'Fresh Lime Juice (Persiano)'),
(142, 'Agave Syrup (1/2 Water + 1/2 Agave Nectar)'),
(143, 'White Smooth Grappa'),
(144, 'Honey mix (replace water with chamomile)'),
(145, 'Chamomile cordial'),
(146, 'Sweet Vermouth'),
(147, U&'Be\00b4ne\00b4dictine'),
(148, 'Egg White (Optional)'),
(149, 'Jamaican dark rum'),
(150, 'Gold Puerto Rican rum'),
(151, 'Demerara Rum'),
(152, U&'Donn\2019s Mix'),
(153, 'Pernod');       
